services:
  - type: cron
    name: zap-imoveis-scheduler
    runtime: python
    schedule: "0 8 * * *"
    buildCommand: "pip install -r requirements.txt && playwright install"
    startCommand: "python main.py"
